--- # Gather EC2 Facts from my remote isntance(s)
- hosts: aws
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Gather the EC2 Facts about running instance(s)
    action: ec2_facts
  - name: Display the instance type
    debug: msg='{{ ansible_ec2_instance_type }}'
