--- # EC2_KEY MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  var_files: 
  - keys/aws_keys.yml
  tasks:
  - name: Create a New Key Pair - MyKeyPairTestAWS
    ec2_key: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      name: MyKeyPairTestAWS
      region: us-wes-2
      state: present
